version: "3"

services:
  ue:
    build: ./ue
    tty: true
    ports:
      - "5201:5201"
    networks:
      s1:
        ipv4_address: 10.0.10.10
  sgw:
    build: ./sgw
    tty: true
    networks:
      s1:
        ipv4_address: 10.0.10.20
      s5:
        ipv4_address: 10.0.11.10
  upgw:
    build: ./upgw
    tty: true
    networks:
      s5:
        ipv4_address: 10.0.11.20
      sgi:
        ipv4_address: 10.0.12.10
  gw:
    build: ./gw
    tty: true
    networks:
      sgi:
        ipv4_address: 10.0.12.20

networks:
  s1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
  s5:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24
  sgi:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.12.0/24



    